name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download cucumber-json-format tool
        run: |
          wget https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-amd64 -O /usr/local/bin/cucumber-json-formatter
          chmod +x /usr/local/bin/cucumber-json-formatter
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Export scenarios from Xray and generate .feature file(s)
        run: |
          BASE_URL=https://xray.cloud.getxray.app
          KEYS="APT-13"
          token=$(curl -H "Content-Type: application/json" -X POST --data @"cloud_auth.json" "$BASE_URL/api/v2/authenticate"| tr -d '"')
          curl -H "Content-Type: application/json" -X GET -H "Authorization: Bearer $token" "$BASE_URL/api/v2/export/cucumber?keys=$KEYS" -o features.zip
          rm -rf features/*.feature
          unzip -o features.zip -d features
      - name: Cypress run
        continue-on-error: true
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --spec 'features/**/*.feature'
          #command: npx cypress run --record --spec 'features/**/*.feature'
          record: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Import results to Xray (cloud) using multipart endpoint
        run: |
          BASE_URL=https://xray.cloud.getxray.app
          token=$(curl -H "Content-Type: application/json" -X POST --data @"cloud_auth.json" "$BASE_URL/api/v2/authenticate"| tr -d '"')
          curl -H "Content-Type: application/json" -X POST -H "Authorization: Bearer $token"  --data @"cucumber-report.json" "$BASE_URL/api/v2/import/execution/cucumber"
