name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Export scenarios from Xray and generate .feature file(s)
        run: |
          BASE_URL=https://xray.cloud.getxray.app
          KEYS="AP-2;AP-3"
          token=$(curl -H "Content-Type: application/json" -X POST --data @"cloud_auth.json" $BASE_URL/api/v2/authenticate| tr -d '"')
          curl -H "Content-Type: application/json" -X GET -H "Authorization: Bearer $token" "$BASE_URL/api/v2/export/cucumber?keys=$KEYS" -o features.zip
          rm -rf features/*.feature
          unzip -o features.zip -d features
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --record
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
